app/models.py
import os
import markovify
import tweepy
from app import db, login, twitter_auth
from flask_login import UserMixin
from config import BASEDIR

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    twitter_id = db.Column(db.Integer)
    access_token = db.Column(db.String(128))
    access_token_secret = db.Column(db.String(128))
    frequency = db.Column(db.String(128))
    like_all = db.Column(db.Boolean)
    like_timestamp = db.Column(db.Integer)
    follow_back = db.Column(db.Boolean)
    follow_timestamp = db.Column(db.Integer)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def get_tweet(self):
        return self.get_text_model().make_short_sentence(280)

    def tweet(self, text=None):
        if not text:
            text = self.get_tweet()
        
        self.get_twitter_api().update_status(text)

    def get_text_model(self):
        if not hasattr(self, '_text_model'):
            path = os.path.join(BASEDIR, "data", "{}.json".format(self.id))
            with open(path) as f:
                self._text_model = markovify.Text.from_json(f.read())
        return self._text_model

    def get_twitter_api(self):
        if not hasattr(self, '_api'):
            auth = twitter_auth()
            auth.set_access_token(self.access_token, self.access_token_secret)
            self._api = tweepy.API(auth)
        return self._api

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, BooleanField, SubmitField

class SettingsForm(FlaskForm):
    frequency = SelectField('Frequency', choices=[('every', 'Every Hour'), ('even', 'Even Hours'), ('odd', 'Odd Hours'), ('4', 'Every 4 Hours'), ('6', 'Every 6 Hours'), ('8', 'Every 8 Hours'), ('12', 'Every 12 Hours')])
    like_all = BooleanField('Like all retweets?')
    follow_back = BooleanField('Follow everyone who follows you?')

    submit = SubmitField('Save')


    

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import tweepy
from flask_login import LoginManager
from logging.handlers import RotatingFileHandler


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
def twitter_auth():
    return tweepy.OAuthHandler(Config.CONSUMER_KEY, Config.CONSUMER_SECRET)

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.connect import bp as connect_bp
    app.register_blueprint(connect_bp, url_prefix='/connect')

    from app import models

    if not app.debug and not app.testing:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/sushibots.log', maxBytes=10240,
                                        backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('SushiBots startup')

    return app

app/connect/__init__.py
from flask import Blueprint

bp = Blueprint('connect', __name__)

from app.connect import routes

app/connect/routes.py
from flask import render_template, flash, redirect, url_for, request, session, current_app
import tweepy
from flask_login import current_user, login_user
from app.models import User
from app import db, twitter_auth
from app.connect import bp

@bp.route('/')
@bp.route('/index')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    auth = twitter_auth()
    redirect_url = auth.get_authorization_url()
    session['oauth_token'] = auth.request_token['oauth_token']

    return render_template('connect/index.html', title='Connect Account', auth_url=redirect_url)

@bp.route('/callback')
def callback():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    token = request.args.get("oauth_token")
    verifier = request.args.get("oauth_verifier")

    auth = twitter_auth()
    
    auth.request_token = { 'oauth_token' : token, 'oauth_token_secret' : verifier }

    #try:
    auth.get_access_token(verifier)
    username = auth.get_username()
    api = tweepy.API(auth)
    user_info = api.get_user(username)
    twitter_id = user_info.id

    # If we can find user, great!
    user = User.query.filter_by(twitter_id=twitter_id).first()
    if not user:
        user = User(username=username, twitter_id=twitter_id, access_token=auth.access_token, access_token_secret=auth.access_token_secret)
        db.session.add(user)
        db.session.commit()
    
    login_user(user, remember=True)
    return redirect(url_for('main.index'))
    #except tweepy.TweepError:
    #    return 'Error! Failed to get access token.'

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, session
from flask_login import current_user
from app.main import bp
from app.main.forms import SettingsForm
from app.models import User
from app import db

@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html')

@bp.route('/settings', methods=['GET', 'POST'])
def settings():
    form = SettingsForm()
    if form.validate_on_submit():
        data = {
            'frequency': form.frequency.data,
            'like_all': form.like_all.data,
            'follow_back': form.follow_back.data,
        }
        User.query.update(data)
        db.session.commit()
        flash('saved it all!')
    form = SettingsForm(obj=current_user)
    return render_template('settings.html', form=form, user=current_user)

app/templates/base.html
<html>
    <head>
      {% if title %}
      <title>{{ title }} - SushiBot</title>
      {% else %}
      <title>Welcome to SushiBot</title>
      {% endif %}
    </head>
    <body>
        <div>
            SushiBot: 
            <a href="{{ url_for('main.index') }}">Home</a>
            <a href="{{ url_for('connect.index') }}">Login</a>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        <hr>
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/connect/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Connect Account</h1>
    <a href="{{ auth_url }}">Connect Account</a>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
        <h1>Hello!</h1>
{% endblock %}

app/templates/settings.html
{% extends "base.html" %}

{% block content %}
    <h1>Settings for {{ current_user.username }}</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.frequency.label }}<br>
            {{ form.frequency() }}
        </p>
        <p>
            {{ form.like_all() }}
            {{ form.like_all.label }}
            
        </p>
        <p>
            {{ form.follow_back() }}
            {{ form.follow_back.label }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}